CREATE TABLE IF NOT EXISTS tag (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(200) NOT NULL,
	color CHAR(6)
);

CREATE TABLE IF NOT EXISTS post_tag (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	post_id INT,
	tag_id INT,
	CONSTRAINT FK_PostID FOREIGN KEY (post_id) REFERENCES post(id),
	CONSTRAINT FK_TagID FOREIGN KEY (tag_id) REFERENCES tag(id)
);
